apiVersion: v1
kind: Service
metadata:
  name: quantified
  labels:
    app: quantified
spec:
  ports:
    - port: 80
      name: quantified
  selector:
    app: quantified
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantified
  labels:
    app: quantified
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quantified
  template:
    metadata:
      labels:
        app: quantified
    spec:
      containers:
      - name: quantified
        image: crsmithdev/quantified
        ports:
        - containerPort: 80
